name: generate_index
"on":
    push:
jobs:
    generate_index:
        strategy:
            matrix:
                python-version: ["3.10"]
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        permissions:
            contents: write
        steps:
          - name: Checkout
            uses: actions/checkout@v3.4.0
          - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v4.5.0
            with:
              python-version: ${{ matrix.python-version }}
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install requests pytz
          - name: Get Diff Action
            uses: technote-space/get-diff-action@v4.0.1
            with:
              PATTERNS: |
                missions/**/*.py
              FILES: |
                index.json
                index_zh_CN.json
                index_en_US.json
          - name: Generate Index
            run: |
              python ./workflows/generate_index.py -i ${{ env.GIT_DIFF_FILTERED }}
            if: env.GIT_DIFF && env.GIT_DIFF_FILTERED
          - name: Commit Changes
            uses: EndBug/add-and-commit@v9.1.3
            with:
                author_name: ${{ env.ALL_AUTHORS }}
                author_email: ${{ env.ALL_AUTHORS }}
                committer_name: github-actions[bot]
                committer_email: github-actions[bot]@users.noreply.github.com
                message: ':wrench: Generate Index by GitHub Actions'
                add: |
                  'index.json'
                  'index_zh_CN.json'
                  'index_en_US.json'
    