name: PR_check
"on":
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
    push:
jobs:
    PR_check:
        strategy:
            matrix:
                python-version: ["3.10"]
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3.4.0
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4.5.0
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install requests
            - name: Get Diff Action
              uses: technote-space/get-diff-action@v4.0.1
              with:
                PATTERNS: |
                  missions/**/*.py
                FILES: |
                  index.json
                  index_zh_CN.json
                  index_en_US.json
            - name: Check Index Modifications
              run: |
                python ./workflows/check_index_modifications.py
              if: env.GIT_DIFF && env.MATCHED_FILES
            - name: Validate Mission File
              run: |
                python ./workflows/validate_mission_file.py -i ${{ env.GIT_DIFF_FILTERED }}
              if: env.GIT_DIFF && env.GIT_DIFF_FILTERED